config/routes.rb
Rails.application.routes.draw do
  # Admin routes for ActiveAdmin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Static pages
  get 'static_pages/:title', to: 'static_pages#show', as: :static_page

  # Products and categories
  resources :products, only: [:index, :show]
  resources :categories, only: [:show]

  # User authentication
  devise_for :users, controllers: { registrations: 'users/registrations' }

  # Orders routes
  resources :orders, only: [:index, :show, :create, :new, :edit, :update]

  # Carts and cart items
  resources :carts, only: [:show] do
    resources :cart_items, only: [:create, :update, :destroy]
  end

  # Root and other pages
  root 'home#index'
  get 'collections', to: 'pages#collections'
  get 'casual', to: 'pages#casual'
  get 'sports', to: 'pages#sports'
  get 'about', to: redirect('/static_pages/about')
  get 'contact', to: redirect('/static_pages/contact')

  # Search route
  get 'search_products', to: 'home#index', as: :search_products

  # Additional routes
  get 'orders/get_tax_rates', to: 'orders#get_tax_rates'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sneakers</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
  <%= stylesheet_link_tag 'custom', media: 'all', 'data-turbo-track': 'reload' %>
  <%= stylesheet_link_tag 'orders', media: 'all', 'data-turbo-track': 'reload' %>
   <%= stylesheet_link_tag 'invoice', media: 'all', 'data-turbo-track': 'reload' %>
  <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
  <%= javascript_include_tag 'application' %>
  <!-- Stripe.js -->
  <script src="https://js.stripe.com/v3/"></script>

</head>
<body>
  <header>
    <div class="container">
      <div class="d-flex justify-content-between align-items-center py-3">
        <!-- Logo -->
        <div class="logo">
          <%= link_to root_path do %>
            <%= image_tag 'logo.svg', alt: 'Logo', class: 'logo-image' %>
          <% end %>
        </div>

        <!-- Navigation Menu -->
        <nav>
          <ul class="nav">
            <li class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle" id="categoriesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
              <div class="dropdown-menu" aria-labelledby="categoriesDropdown">
                <% Category.all.each do |category| %>
                  <a class="dropdown-item" href="<%= category_path(category) %>"><%= category.name %></a>
                <% end %>
              </div>
            </li>
            <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "Contact", contact_path, class: "nav-link" %></li>
          </ul>
        </nav>

        <!-- User Menu -->
        <div class="user-menu">
          <% if user_signed_in? %>
            <div class="user-info">
              <p class="mb-0">Welcome, <%= current_user.email %></p>
              <% if current_user.cart %>
                <%= link_to "Cart", cart_path(current_user.cart.id), class: "cart-link" %>
              <% else %>
                <p>Your cart is not available.</p>
              <% end %>
              <%= link_to "View My Orders", orders_path, class: "orders-link" %>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "logout-link" %>
            </div>
          <% else %>
            <%= link_to "Login", new_user_session_path, class: "login-link" %>
          <% end %>
        </div>
      </div>
    </div>
  </header>

  <main>
    <%= yield %>
  </main>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
</body>
</html>